# Generated by Django 5.0.3 on 2024-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=128)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_description", models.CharField(max_length=32)),
                ("end_description", models.CharField(max_length=32)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ("-start_date", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[("WORK", "Work"), ("VOLUNTEER", "Volunteer")],
                        max_length=10,
                    ),
                ),
                ("organisation", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=128)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_description", models.CharField(max_length=32)),
                ("end_description", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("highlight", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "ordering": ("-start_date", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Trivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("highlight", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Trivia",
                "verbose_name_plural": "Trivia",
                "ordering": ("order", "pk"),
            },
        ),
    ]
