# Generated by Django 5.0.3 on 2024-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitae", "0004_personaldata_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldata",
            name="position",
            field=models.TextField(default="Developer"),
            preserve_default=False,
        ),
    ]
