# Generated by Django 5.0.3 on 2024-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitae", "0005_personaldata_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldata",
            name="email",
            field=models.TextField(default="example at example dot com"),
            preserve_default=False,
        ),
    ]
